#!/bin/bash

while getopts s:t:r: options; do
   case ${options} in
      s) HIGECO=${OPTARG} ;;
      t) TYPE=${OPTARG} ;;
      r) REBOOTED=${OPTARG} ;;
   esac
done

declare -a RESPONSE=()

if ! [ -v JQ ] ; then
  RESPONSE+=("Export: Specifies the JQ.")
fi

if ! [ -v CURL ] ; then
  RESPONSE+=("Export: Specifies the CURL.")
fi

if ! [ -v MYSQL ] ; then
  RESPONSE+=("Export: Specifies the MYSQL.")
fi

if ! [ -v WORKER ] ; then
  RESPONSE+=("Export: Specifies the WORKER.")
fi

if ! [ -v IPCALC ] ; then
  RESPONSE+=("Export: Specifies the IPCALC.")
fi

if ! [ -v SSHPASS ] ; then
  RESPONSE+=("Export: Specifies the SSHPASS.")
fi

if ! [ -v GREPCIDR ] ; then
  RESPONSE+=("Export: Specifies the GREPCIDR.")
fi

if ! [ -v HIGECO ] ; then
  RESPONSE+=("-s: Specifies the higeco.")
fi

if ! [ -v TYPE ] ; then
  RESPONSE+=("-t: Specifies the plugin.")
fi

if [ ${#RESPONSE[@]} -ne 0 ] ; then
  printf '%s\n' "${RESPONSE[@]}"
  exit 1;
fi

unset RESPONSE
