#!/bin/bash

source $SOURCE/argument "$@"

FORTIGATE_HOST="https://${FORTIGATE}:${FORTIGATE_PORT}"
PROXY_CONNECTION="http://${PROXY}:${PROXY_PORT}/"

decode() {
    echo "$1" | base64 -d | $JQ -rc "${2}"
    return 0
}

GetFromQuerystring() {
    echo "$1" | awk -v key="$2" -F "[=&]" '{for (i=1; i<=NF; i++) if ($i == key) print $(i+1)}'
    return 0
}

ObtainProxyPass() {
    local query='SELECT `connectivity_ip`, `connectivity_port`, `connectivity_protocol`, `connectivity_type` FROM `energia_europa_higeco_get_connection_information` WHERE `serial_higeco` = "%s" LIMIT 1';
    printf "$query" "$1" | $MYSQL -s -w -u${DATABASE_USERNAME} -p${DATABASE_PASSWORD} -h ${DATABASE_ENDPOINT} --port=${DATABASE_PORT} --database ${DATABASE} | awk '{printf "host=%s&port=%s&protocol=%s&type=%s", $1, $2, $3, $4}'
    return 0
}

PROXY_CONNECTION_PASS=$(ObtainProxyPass "$HIGECO")

ObtainFortigate() {
    local EXTRACTOR='.results[] | {net:.proxyid[].proxy_dst[].subnet,peer:.rgwy} | @base64'
    $CURL -k -G -d "access_token=ps3hzHnn3xmj15xkpjfykNsGczq8tj" --silent --connect-timeout 24 --retry 4 "${FORTIGATE_HOST}/api/v2/monitor/vpn/ipsec" | $JQ -rc "$EXTRACTOR"
    return 0
}

OpenSSH() {
    [ -z "${IP}" ] && IP=$(GetFromQuerystring "$PROXY_CONNECTION_PASS" 'host')
    $SSHPASS -p $ROOT $SSH -p $1 -o StrictHostKeyChecking=no -o ConnectTimeout=120 -Tq root@$IP "$2"
    return 0
}

Retry() {
    local -r cmd="$1"
    local -i retries=0
    while true; do
        retries+=1
        if [ $retries -ge 4 ] ; then
            return 2
        fi
        local response=$($cmd)
        if ! [ -z "$response" ] ; then
            echo $response
            return 0
        fi
        sleep 24
    done
    return 1
}

ip2int() {
    local ipa=$(echo "${1}" | cut -d '.' -f1)
    local ipb=$(echo "${1}" | cut -d '.' -f2)
    local ipc=$(echo "${1}" | cut -d '.' -f3)
    local ipd=$(echo "${1}" | cut -d '.' -f4)

    echo $(( ipa * 256**3 + ipb * 256**2 + ipc * 256 + ipd ))

    return 0
}

check() {
    local response=1
    local subnet=$(echo "${1}" | cut -d '/' -f1)
    local cidr=$(echo "${1}" | cut -d '/' -f2)
    local netmask=$(( 0xFFFFFFFF << $(( 32 - ${cidr} )) ))
    local id=$(( netmask & $(ip2int "${2}") ))
    local subnet=$(( netmask & $(ip2int "${subnet}") ))

    [ "${id}" = "${subnet}" ] && response=0

    return $response
}

getPeer() {
    [ -z "${FORTIGATE_DATA}" ] && FORTIGATE_DATA=$(ObtainFortigate)
    for item in ${FORTIGATE_DATA[@]}; do
        local net=$(decode $item '.net')
        local peer=$(decode $item '.peer')
        if [ "$net" = "0.0.0.0-255.255.255.255" ] ; then
            continue
        fi
        if [[ "$net" == *"/"* ]] ; then
            local max=$($IPCALC --maxaddr "$net" | sed 's/MAXADDR=//g')
            local min=$($IPCALC --minaddr "$net" | sed 's/MINADDR=//g')
            local net="${min}-${max}"
        fi
        local cidr=$($IPCALC -d "$net" | sed -n '2p' | awk '{print $2}')
        check "$cidr" "${1}"
        if [ $? -eq 0 ] ; then
            echo $peer
            return 0
        fi
    done
    return 1
}

getGateway() {
    OpenSSH ${1} "ip route | grep default | grep -v linkdown | awk '{print \$3}' | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'"
    return 0
}

getInterface() {
    OpenSSH ${1} "ip route show default | grep -v linkdown | awk '/default via/ {print \$5}'"
    return 0
}

getPrivate() {
    OpenSSH ${1} "ip -4 -brief address show $2 | awk '{print \$NF}'"
    return 0
}

getMAC() {
    OpenSSH ${1} "ip n show $2 | awk '{print \$5}'"
    return 0
}

getOUI() {
    local EXTRACTOR='.result.company'
    $CURL -k --silent --connect-timeout 24 --retry 4 "https://macvendors.co/api/$3" | $JQ -rc "${EXTRACTOR}"
    return 0
}

getISP() {
    local EXTRACTOR='.org'
    $CURL -k --silent --connect-timeout 24 --retry 4 "https://ipinfo.io/$3/json" | $JQ -rc "${EXTRACTOR}"
    return 0
}

getSSHPort() {
    local QUERY='[{"act":"getServerStatus","DATI":{}}]'
    local EXTRACTOR='.DATI[0].DATI[0].sshPort'
    local SSHPORT=$($CURL -s -k -X POST --compressed "$PROXY_CONNECTION/serverCgi?${PROXY_CONNECTION_PASS}" -b "$1" --silent --connect-timeout 24 --retry 4 --data-urlencode "query=$QUERY" | $JQ -rc "${EXTRACTOR}")
    if [ -z "${SSHPORT}" ] ; then
        return 1
    fi
    echo $SSHPORT
    return 0
}

insert() {
    local array=()
    local QUERY='INSERT INTO `energia_europa_higeco_get_connection_information_output` (`serial_higeco`, `gateway`, `private`, `nat`, `mac`, `oui`, `isp`, `ip`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s) ON DUPLICATE KEY UPDATE `gateway` = VALUES(`gateway`), `private` = VALUES(`private`), `nat` = VALUES(`nat`), `mac` = VALUES(`mac`), `oui` = VALUES(`oui`), `isp` = VALUES(`isp`), `ip` = VALUES(`ip`)';
    for i in "$@" ; do
        local value='NULL'
        [[ "$i" != "NULL" ]] && ! [[ -z "${value}" ]] && value=$(printf '"%s"' "$i")
        array+=("$value")
    done
    printf "$QUERY" "${array[0]}" "${array[1]}" "${array[2]}" "${array[3]}" "${array[4]}" "${array[5]}" "${array[6]}" "${array[7]}" |
        $MYSQL -s -w -u${DATABASE_USERNAME} -p${DATABASE_PASSWORD} -h ${DATABASE_ENDPOINT} --port=${DATABASE_PORT} --database ${DATABASE}
    if [ $? -ne 0 ] ; then
        printf '{"status": false, "device": "%s", "notice": "%s"}' "${1}" "I was unable to execute insert query"
        return 1
    fi
    return 0
}

connectivity() {
    local QUERY='[{"act":"getStatus"}]'
    local status=$($CURL -k -s -X POST --data "query=${QUERY}" --output /dev/null --connect-timeout 24 --retry 4 --write-out '%{http_code}\n' --compressed "$PROXY_CONNECTION/userCgi?${PROXY_CONNECTION_PASS}")
    if [ "200" = "$status" ] ; then
        return 0;
    fi
    return 1
}

authorization() {
    local QUERY='[{"act":"getStatus"}]'
    local EXTRACTOR='.DATI[0].DATI'
    local CONFIGURATION=$($CURL -s -k -X POST --compressed "$PROXY_CONNECTION/userCgi?${PROXY_CONNECTION_PASS}" --silent --connect-timeout 24 --retry 4 --data "p=$PASSWORD&u=$USERNAME&query=$QUERY" | $JQ -rc "${EXTRACTOR}")
    if [ -z "${CONFIGURATION}" ] ; then
        printf '{"status": false, "device": "%s", "notice": "%s"}' "${1}" "Is unreachable"
        exit 1
    fi
    local AUTHORIZATION=$($JQ -rc .k <<< "${CONFIGURATION}")
    echo "gwc=$AUTHORIZATION"
    return 0
}

restart() {
    local QUERY='[{"act":"rbtStm","DATI":{}}]'
    local QUERY=$(printf "$QUERY" ${1})
    local EXTRACTOR='.DATI[0].ERR'
    local DATA=$($CURL -s -k -X POST --compressed "$PROXY_CONNECTION/mainGwcCgi?${PROXY_CONNECTION_PASS}" -b "$3" --silent --connect-timeout 24 --retry 4 --data-urlencode "query=$QUERY" | $JQ -rc "${EXTRACTOR}")
    if [ -z "${DATA}" ] || [ "$DATA" -ne 0 ] ; then
        printf '{"status": false, "device": "%s", "notice": "%s"}' "${1}" "Not execute reboot. Complete operation in manual mode."
        exit 1
    fi
    return 0
}

modem() {
    local QUERY='[{"act":"getInfo","sn":"%s","DATI":{}}]'
    local QUERY=$(printf "$QUERY" "${1}")
    local AUTHORIZATION=$(authorization ${1})
    local EXTRACTOR='.DATI[0].DATI.ppp0.modem.manufacturer + " -> " + .DATI[0].DATI.ppp0.modem.model'
    local MODEM=$($CURL -s -k -X POST --compressed "$PROXY_CONNECTION/connection.cgi?${PROXY_CONNECTION_PASS}" -b "$AUTHORIZATION" --silent --connect-timeout 24 --retry 4 --data-urlencode "query=$QUERY" | $JQ -rc "${EXTRACTOR}")
    if [ -z "${MODEM}" ] ; then
        return 1
    fi
    echo $MODEM
    return 0 
}

obtain() {
    local TYPE=$(GetFromQuerystring "$PROXY_CONNECTION_PASS" 'type')
    local WEBPORT=$(GetFromQuerystring "$PROXY_CONNECTION_PASS" 'port')
    local SSHPORT=$(($WEBPORT + 1))
    if [ "$TYPE" = "ipsec-dialup" ] || [ "$TYPE" = "ipsec-ptp" ] ; then
        SSHPORT=22
    elif [ "$TYPE" = "higeco-backdoor" ] ; then
        local AUTHORIZATION=$(authorization ${1})
        if [ -z "${REBOOTED}" ] || [[ $REBOOTED -ne 1 ]] ; then
            local ARGUMENTS="${@}"
            local ARGUMENTS=$(echo -e $ARGUMENTS | cut -d ' ' -f3-)
            restart $1 "$AUTHORIZATION"
            sleep 180
            echo $($WORKER $ARGUMENTS -r 1)
            exit 0;
        fi
        local COMMAND=$(printf 'getSSHPort "%s"' "$AUTHORIZATION")
        local SSHPORT=$(Retry "$COMMAND")
        if [ -z "${SSHPORT}" ] ; then
            printf '{"status": true, "device": "%s", "notice": "%s"}' "${1}" "JSON as response not contain a valid TCP port."
            exit 1
        fi
    fi
    local interface=$(getInterface $SSHPORT)
    local gateway=$(getGateway $SSHPORT)
    local private=$(getPrivate $SSHPORT "$interface")
    if [ -z "$interface" ] || [ -z "$gateway" ] || [ -z "$private" ] ; then
        return 2
    fi
    local public=$(GetFromQuerystring "$PROXY_CONNECTION_PASS" 'host')
    local nat=$(GetFromQuerystring "$PROXY_CONNECTION_PASS" 'host')
    if [ "$TYPE" = "ipsec-dialup" ] || [ "$TYPE" = "ipsec-ptp" ] ; then
        public=$(getPeer "$nat")
    fi
    local isp=$(getISP $SSHPORT "$TYPE" "$public")
    if [ "$interface" != "ppp0" ] ; then
        local mac=$(getMAC $SSHPORT "$gateway")
        local oui=$(getOUI $SSHPORT "$TYPE" "$mac")
    else
        local mac="00:00:00:00:00:00"
        local oui=$(modem "$HIGECO")
    fi
    insert "$1" "$gateway" "$private" "$nat" "$mac" "$oui" "$isp" "$public"
    if [ $? -ne 0 ] ; then
        return 1
    fi
    local time=$(date '+%Y-%m-%d %H:%M')
    local output='{"status": true, "device": "%s", "data": {"gateway": "%s", "private": "%s", "nat": "%s", "mac": "%s", "oui": "%s", "isp": "%s", "public": "%s", "last": "%s"}}'
    printf "${output}" "${HIGECO}" "${gateway}" "${private}" "${nat}" "${mac}" "${oui}" "${isp}" "${public}" "${time}"
    return 0
}

connectivity
if [ $? -ne 0 ] ; then
    printf '{"status": false, "device": "%s", "notice": "%s"}' "${HIGECO}" "Have an inbound connectivity problem."
    exit 1
fi

obtain $HIGECO "$@"
errors=$?
if [ $errors -ne 0 ] ; then
    echo "${HIGECO} - Have a problem #$errors"
    printf '{"status": false, "device": "%s", "notice": "%s"}' "${HIGECO}" "Have a problem."
    exit 1
fi

exit 0
